version: '3'

services:
    proxy-app:
        image: nginx:latest
        container_name: proxy-app
        volumes: 
            - ./app/index.html:/etc/nginx/html/index.html
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        ports: 
            - 8080:80
        networks:
            monitoring:
                aliases:
                    - proxy-app

    proxy-prometheus-exporter:
        image: nginx/nginx-prometheus-exporter:latest
        container_name: proxy-prometheus-expo
        ports:
            - 9113:9113
        environment:
            - SCRAPE_URI=http://proxy-app:80/stub_status
            - TELEMETRY_PATH=/metrics
            - RETRIES=5
            - TIMEOUT=5s
        networks:
            monitoring:
                aliases:
                    - proxy-prometheus-exporter
        
    prometheus:
        image: prom/prometheus:latest
        container_name: prometheus
        ports:
            - 9090:9090
        volumes:
            - ./prometheus//prometheus.yaml:/etc/prometheus/prometheus.yml
            - ./prometheus/rules.yaml:/etc/prometheus/rules.yaml
        networks:
            monitoring:
                aliases:
                    - prometheus
    
    alertmanager: 
        image: prom/alertmanager:latest
        container_name: alertmanager
        ports:
            - "9093:9093"
        volumes:
            - ./alertmanager/alertmanager.yaml:/etc/alertmanager/alertmanager.yaml 
        networks:
            monitoring:
                aliases:
                    - alertmanager
networks:
    monitoring: