
# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - 'rules.yaml'

# Alerting specifies settings related to the Alertmanager
alerting:
  alertmanagers:
    - scheme: http
      path_prefix: "/"
      static_configs:
        - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']
      
  - job_name: 'proxy-exporter'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['proxy-prometheus-exporter:9113']

  - job_name: 'nginx'
    metrics_path: /stub_status
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://proxy-app:80
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: proxy-prometheus-exporter:9115