
# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - 'rules.yaml'

# Alerting specifies settings related to the Alertmanager
alerting:
  alertmanagers:
    - scheme: http
      path_prefix: "/"
      static_configs:
        - targets: ['am:9093']

scrape_configs:
  - job_name: 'proxy-exporter'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['proxy-prometheus-exporter:9113']
