groups:
- name: InstanceStatus
  rules:
  # Alert for any instance that is unreachable for >10 seconds.
  - alert: NginxServerDown
    expr: nginx_up == 0
    for: 20s
    labels:
      severity: critical
    # Prometheus templates apply here in the annotation and label fields of the alert.
    annotations:
      description: "Proxy app is down for more than 10 seconds"
      summary: "Nginx server hosting app is down"
  
  - alert: ExporterDown
    expr: up == 0
    for: 20s
    labels:
      severity: critical
    # Prometheus templates apply here in the annotation and label fields of the alert.
    annotations:
      description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes."
      summary: "Instance {{ $labels.instance }} down"
